### ISSUE TITLE
How to connect the sensor to arduino or raspberry pi

### ISSUE THREAD

**Issue by jomfawad** [Aightech/CleverHand-EMG#3]
I have question can i control this emg sensor directly with  arduino or raspberry pi without using the spi bus in this schematic? and if it works and i want to connect the sensor to the arduino how do i connect it? because there isnt wires, if you could please explain how to connect it step by step to arduino and which code to use to be able to read signals from the sensor and see them in arduino ide serial monitor? Thank you in advance

**Comment by Aightech** [comment]
Yes you can connect my little modules on an Arduino.
Here is the repo for the interfacing code https://github.com/Aightech/CleverHand-interface more specifically the arduino code :https://github.com/Aightech/CleverHand-interface/tree/main/src/uctrl_master

I will make some videos explaining the project and how to make it yourself by the end of September ;)
